#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx tsc --noEmit && npx eslint . && npx prettier --write .
npx tsc --noEmit && npx eslint . && npx prettier --write . && git add .
npx tsc --noEmit && npx eslint . && npx prettier --write . && git add .
